stages:
  - test

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

formal:
  stage: test
  image: ubuntu:jammy
  before_script:
    - export PATH="/root/.local/bin:$PATH"
    - apt-get update
    - apt-get install -y
        git
        python3-pip
        sudo
    - ./init
    - pip3 install sandpiper-saas --user
    - cd formal
    - ./make_env.sh
  script:
    - make tos_agree verif

.react-build:
  image: node:18
  before_script:
    - cd configurator
    - yarn --frozen-lockfile
  script:
    - yarn build
    - cp -r build/ ../public/
  artifacts:
    paths:
      - public

react-build:
  stage: test
  extends:
    - .react-build
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

pages:
  stage: test
  extends:
    - .react-build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
